version: '2'

services:
  test:
    build: .
    command: bash -c "python manage.py test"

    volumes:
      - .:/code

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: api-task

    ports:
    - "8000:8000"

    volumes:
      - .:/code